### ISSUE TITLE
connectd depends on ca-certificates

### ISSUE THREAD

**Issue by nconder** [remoteit/installer#106]
Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-86-generic x86_64)

Ive tried updating the CA certs but did not work. Any other ideas?
> update-ca-certificates --verbose --fresh

> Downloading and testing connectd.x86_64-ubuntu16.04...
> connectd.x86_64-ubuntu16.04 is compatible!
> filename connectd_2.4.26_amd64.deb
> filepath https://github.com/remoteit/installer/releases/download/v2.4.26/connect                    d_2.4.26_amd64.deb
> Selecting previously unselected package connectd.
> (Reading database ... 220863 files and directories currently installed.)
> Unpacking connectd (from connectd_2.4.26_amd64.deb) ...
> **dpkg: dependency problems prevent configuration of connectd:
>  connectd depends on ca-certificates (>= 20161130+nmu1+deb9u1); however:
>   Version of ca-certificates on system is 20160104ubuntu0.12.04.1.**
> dpkg: error processing connectd (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  connectd
> dpkg error!

**Comment by Digital-Larry** [comment]
We have removed the dependency on a specific version of ca-certificates.
