### ISSUE TITLE
schannel running after installation but Systemd services inactive

### ISSUE THREAD

**Issue by kevinburkemeter** [remoteit/installer#64]
I just completed the installer on Ubuntu 18.04. I observe that connectd_schannel and connectd_processes are running on the host. However, both systemd units are inactive.

```
systemctl status connectd_schannel
● connectd_schannel.service - Remote tcp command service
   Loaded: loaded (/lib/systemd/system/connectd_schannel.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

```
# ps aux | grep connectd
root      8033  0.0  0.0  11540  2324 ?        S    20:12   0:00 /usr/bin/connectd.x86_64-ubuntu16.04 ...
root      8055  0.0  0.0   4536   128 ?        S    20:12   0:00 /usr/bin/connectd_schannel.x86_64-ubuntu16.04 -f /etc/connectd/schannel.conf -d /var/run/connectd_schannel.x86_64-ubuntu16.04.pid
root      8380  0.0  0.0  11540  2188 ?        S    20:14   0:00 /usr/bin/connectd.x86_64-ubuntu16.04 ...
```

As a result I'm unsure about the best way to supervise the process.

**Comment by kevinburkemeter** [comment]
Aha, it looks like there's a crontab installed:

```
# crontab -l
@reboot /usr/bin/connectd_start_all
```

How can I get the installer to skip the crontab and instead use systemd to manage processes?

**Comment by kevinburkemeter** [comment]
If you're running into this, it's because the auto installer installs v2 by default. The `master` branch has been updated to use a different installation procedure, but that's not the one that is installed by the auto installer.

**Comment by Digital-Larry** [comment]
I can't remember when we switched over but we no longer use cron for service startup.  It's all handled by systemd now.
