### ISSUE TITLE
Is v3 ready for production use?

### ISSUE THREAD

**Issue by kevinburkemeter** [remoteit/installer#65]
This library has a v3.0.6 tag, but by default, `scripts/auto-install` tries to install `v2.3.17`.

Is version 3.0.6 ready for production use? If so, why isn't it the default?

**Comment by kevinburkemeter** [comment]
Also FYI scripts/auto-install in the version tagged 3.0.6 still tries to install v2.3.17.

**Comment by kevinburkemeter** [comment]
Further, if it is ready, do you have a guide to upgrade from v2? Thanks.

**Comment by Digital-Larry** [comment]
We abandoned the 3.0.6 branch.  The current version is 2.5.38.
